<?php
namespace Database\Seeders;
use App\Models\{DocumentType,NumberingRule,Permission,Position,Role,Unit,User,Workflow}; use Illuminate\Database\Seeder; use Illuminate\Support\Facades\Hash;
/** Safe development seed: firstOrCreate prevents overwriting existing production records. */
class EOfficeSeeder extends Seeder { public function run():void {
 $permissions=['view documents'=>'Melihat dokumen sendiri','view all documents'=>'Melihat seluruh dokumen','create documents'=>'Membuat dokumen','approve documents'=>'Memproses approval','manage workflows'=>'Mengelola workflow','manage master data'=>'Mengelola master data','view audit logs'=>'Melihat audit log'];foreach($permissions as $name=>$label)Permission::firstOrCreate(['name'=>$name],['label'=>$label]);
 $admin=Role::firstOrCreate(['name'=>'administrator'],['label'=>'Administrator']);$admin->permissions()->syncWithoutDetaching(Permission::pluck('id'));$staff=Role::firstOrCreate(['name'=>'staff'],['label'=>'Staf']);$staff->permissions()->syncWithoutDetaching(Permission::whereIn('name',['view documents','create documents'])->pluck('id'));
 $user=User::firstOrCreate(['email'=>'admin@eoffice.test'],['name'=>'Administrator E-Office','password'=>Hash::make('password')]);$user->roles()->syncWithoutDetaching([$admin->id]);
 foreach(['Rektorat'=>'REK','Fakultas Ilmu Kesehatan'=>'FIK','LPPM'=>'LPPM','LPMI'=>'LPMI'] as $name=>$code)Unit::firstOrCreate(['code'=>$code],['name'=>$name]);
 foreach(['Rektor'=>'REKTOR','WR I'=>'WRI','WR II'=>'WRII','WR III'=>'WRIII','Dekan'=>'DEKAN','Kaprodi'=>'KAPRODI','Dosen'=>'DOSEN','Admin'=>'ADMIN'] as $name=>$code)Position::firstOrCreate(['code'=>$code],['name'=>$name]);
 foreach(['Surat Masuk'=>'INCOMING','Surat Keluar'=>'OUTGOING','Surat Tugas'=>'ASSIGNMENT','Nota Dinas'=>'MEMO','Perjalanan Dinas'=>'BUSINESS_TRIP','Pengajuan Kegiatan'=>'ACTIVITY_REQUEST','Pengajuan Barang'=>'GOODS_REQUEST','Pengajuan Anggaran'=>'BUDGET_REQUEST','Pengajuan SK'=>'DECREE_REQUEST','Pengajuan Surat Keterangan'=>'CERTIFICATE_REQUEST'] as $name=>$code)DocumentType::firstOrCreate(['code'=>$code],['name'=>$name]);
 $assignment=DocumentType::where('code','ASSIGNMENT')->first();$outgoing=DocumentType::where('code','OUTGOING')->first();$fik=Unit::where('code','FIK')->first();NumberingRule::firstOrCreate(['document_type_id'=>$assignment->id,'unit_id'=>$fik->id],['format'=>'{SEQ}/UFDK/{UNIT}/ST/{ROMAN_MONTH}/{YEAR}','reset_period'=>'YEARLY','is_active'=>true]);NumberingRule::firstOrCreate(['document_type_id'=>$outgoing->id,'unit_id'=>null],['format'=>'{SEQ}/UFDK/{UNIT}/SK/{ROMAN_MONTH}/{YEAR}','reset_period'=>'YEARLY','is_active'=>true]);
 $workflow=Workflow::firstOrCreate(['code'=>'SURAT-TUGAS-DOSEN'],['name'=>'Surat Tugas Dosen (Contoh)','document_type_id'=>$assignment->id,'unit_id'=>$fik->id,'is_active'=>true]);if($workflow->wasRecentlyCreated){$workflow->steps()->createMany([['step_order'=>1,'approver_type'=>'ROLE','approver_reference'=>$admin->id,'action'=>'APPROVE','is_required'=>true,'allow_reject'=>true,'allow_revision'=>true],['step_order'=>2,'approver_type'=>'ROLE','approver_reference'=>$admin->id,'action'=>'APPROVE','is_required'=>true,'allow_reject'=>true,'allow_revision'=>true]]);}
 } }
