<?php
use Illuminate\Support\Facades\Route; use App\Http\Controllers\{DashboardController,DocumentController,DispositionController,IncomingLetterController,OutgoingLetterController,WorkflowApprovalController,WorkflowController,InternalDocumentController,NumberingRuleController,VerificationController,DocumentFileController}; use App\Http\Controllers\Auth\AuthenticatedSessionController;
Route::get('/', fn () => auth()->check()
    ? redirect()->route('dashboard')
    : redirect()->route('login')
);
Route::middleware('guest')->group(function(){Route::get('/login',[AuthenticatedSessionController::class,'create'])->name('login');Route::post('/login',[AuthenticatedSessionController::class,'store'])->middleware('throttle:login');});
Route::post('/login/captcha',[AuthenticatedSessionController::class,'refreshCaptcha'])->middleware('guest')->name('login.captcha');Route::post('/logout',[AuthenticatedSessionController::class,'destroy'])->middleware('auth')->name('logout');Route::get('/verifikasi/{token}',[VerificationController::class,'show'])->name('verification.show');
Route::middleware('auth')->group(function(){
Route::get('/dashboard',DashboardController::class)->name('dashboard');Route::resource('documents',DocumentController::class)->only(['index','create','store','show','edit','update']);Route::post('/documents/{document}/resubmit',[DocumentController::class,'resubmit'])->name('documents.resubmit');Route::post('/documents/{document}/files',[DocumentFileController::class,'store'])->name('documents.files.store');Route::get('/documents/{document}/download',[DocumentFileController::class,'download'])->name('documents.download');
Route::get('/documents/{document}/dispositions/create',[DispositionController::class,'create'])->name('dispositions.create');Route::post('/documents/{document}/dispositions',[DispositionController::class,'store'])->name('dispositions.store');Route::get('/dispositions',[DispositionController::class,'index'])->name('dispositions.index');Route::patch('/dispositions/{disposition}/read',[DispositionController::class,'read'])->name('dispositions.read');Route::patch('/dispositions/{disposition}/process',[DispositionController::class,'process'])->name('dispositions.process');Route::patch('/dispositions/{disposition}/complete',[DispositionController::class,'complete'])->name('dispositions.complete');
Route::get('/outgoing-letters',[OutgoingLetterController::class,'index'])->name('outgoing-letters.index');Route::get('/outgoing-letters/create',[OutgoingLetterController::class,'create'])->name('outgoing-letters.create');Route::post('/outgoing-letters',[OutgoingLetterController::class,'store'])->name('outgoing-letters.store');Route::get('/outgoing-letters/{outgoingLetter}',[OutgoingLetterController::class,'show'])->name('outgoing-letters.show');Route::post('/outgoing-letters/{outgoingLetter}/resubmit',[OutgoingLetterController::class,'resubmit'])->name('outgoing-letters.resubmit');
Route::get('/incoming-letters',[IncomingLetterController::class,'index'])->name('incoming-letters.index');Route::get('/incoming-letters/create',[IncomingLetterController::class,'create'])->name('incoming-letters.create');Route::post('/incoming-letters',[IncomingLetterController::class,'store'])->name('incoming-letters.store');Route::get('/incoming-letters/{incomingLetter}',[IncomingLetterController::class,'show'])->name('incoming-letters.show');
Route::get('/internal/{type}/create',[InternalDocumentController::class,'create'])->name('internal-documents.create');Route::post('/internal/{type}',[InternalDocumentController::class,'store'])->name('internal-documents.store');Route::get('/approvals',[WorkflowApprovalController::class,'index'])->name('approvals.index');Route::post('/approvals/{approval}/action',[WorkflowApprovalController::class,'action'])->name('approvals.action');Route::resource('workflows',WorkflowController::class)->except(['show','destroy']);});
Route::middleware('auth')->resource('numbering-rules', NumberingRuleController::class)->only(['index','store','update','destroy']);
Route::middleware('auth')->get('/documents/{document}/final-download',[DocumentFileController::class,'downloadFinal'])->name('documents.final-download');
Route::middleware('auth')->get('/arsip',[\App\Http\Controllers\ArchiveController::class,'index'])->name('archives.index');
Route::middleware('auth')->post('/documents/{document}/start-workflow',[\App\Http\Controllers\DocumentWorkflowController::class,'start'])->name('documents.workflow.start');
Route::middleware('auth')->get('/dispositions/{disposition}',[DispositionController::class,'show'])->name('dispositions.show');
