<?php
namespace Tests\Feature;
use App\Models\{Document,DocumentType,NumberingRule,Permission,Role,Unit,User,Workflow}; use App\Services\WorkflowService; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Str; use Tests\TestCase;
class EOfficeSecurityTest extends TestCase {
 use RefreshDatabase;
 private function user(array $permissions):User{$user=User::factory()->create();$role=Role::create(['name'=>'role-'.Str::random(8),'label'=>'Test']);foreach($permissions as $name){$permission=Permission::firstOrCreate(['name'=>$name],['label'=>$name]);$role->permissions()->attach($permission);}$user->roles()->attach($role);return $user;}
 private function document(User $creator,string $status='DRAFT'):Document{$type=DocumentType::firstOrCreate(['code'=>'TEST'],['name'=>'Test']);return Document::create(['uuid'=>(string)Str::uuid(),'document_type_id'=>$type->id,'creator_id'=>$creator->id,'subject'=>'Dokumen rahasia','status'=>$status,'verification_token'=>Str::random(48)]);}
 public function test_root_redirects_guests_to_login():void{$this->get('/')->assertRedirect(route('login'));}
 public function test_root_redirects_authenticated_users_to_dashboard():void{$this->actingAs($this->user([]))->get('/')->assertRedirect(route('dashboard'));}
 public function test_guest_cannot_access_dashboard():void{$this->get('/dashboard')->assertRedirect('/login');}
 public function test_successful_login_redirects_to_dashboard():void{$user=User::factory()->create(['email'=>'dashboard@example.test','password'=>'password']);$this->withSession(['login_captcha_answer'=>7,'login_captcha_expires_at'=>now()->addMinutes(5)->timestamp])->post('/login',['email'=>$user->email,'password'=>'password','captcha'=>7])->assertRedirect(route('dashboard'));$this->assertAuthenticatedAs($user);}
 public function test_user_with_document_permission_can_access_dashboard():void{$this->actingAs($this->user(['view documents']))->get('/dashboard')->assertOk();}
 public function test_idor_document_view_and_download_are_denied():void{$owner=$this->user(['view documents']);$intruder=$this->user(['view documents']);$document=$this->document($owner);$this->actingAs($intruder)->get(route('documents.show',$document))->assertForbidden();$this->actingAs($intruder)->get(route('documents.download',$document))->assertForbidden();}
 public function test_public_verification_only_works_for_completed_document():void{$creator=$this->user(['view documents']);$document=$this->document($creator,'COMPLETED');$this->get(route('verification.show',$document->verification_token))->assertOk()->assertSee('DOKUMEN VALID')->assertDontSee('Dokumen rahasia');$this->get('/verifikasi/'.Str::random(48))->assertNotFound();}
 public function test_only_configured_approver_can_approve_and_final_step_completes():void{$creator=$this->user(['create documents','view documents']);$approver=$this->user(['approve documents','view documents']);$document=$this->document($creator);$type=$document->type;$unit=Unit::firstOrCreate(['code'=>'TST'],['name'=>'Test']);$document->update(['unit_id'=>$unit->id]);$role=$approver->roles()->first();$workflow=Workflow::create(['name'=>'Test workflow','code'=>'wf-'.Str::random(8),'document_type_id'=>$type->id,'is_active'=>true]);$workflow->steps()->create(['step_order'=>1,'approver_type'=>'ROLE','approver_reference'=>$role->id,'is_required'=>true,'allow_reject'=>true,'allow_revision'=>true]);NumberingRule::create(['document_type_id'=>$type->id,'format'=>'{SEQ}/{YEAR}','reset_period'=>'YEARLY','is_active'=>true]);$instance=app(WorkflowService::class)->start($document,$workflow,$creator);$approval=$instance->approvals()->first();$this->actingAs($creator)->post(route('approvals.action',$approval),['action'=>'APPROVE'])->assertForbidden();$this->actingAs($approver)->post(route('approvals.action',$approval),['action'=>'APPROVE'])->assertRedirect();$this->assertDatabaseHas('documents',['id'=>$document->id,'status'=>'COMPLETED']);$this->assertDatabaseHas('generated_documents',['document_id'=>$document->id]);}
 public function test_approver_can_request_revision_and_creator_can_resubmit():void{$creator=$this->user(['create documents','view documents']);$approver=$this->user(['approve documents','view documents']);$document=$this->document($creator);$role=$approver->roles()->first();$workflow=Workflow::create(['name'=>'Revision','code'=>'rev-'.Str::random(8),'document_type_id'=>$document->document_type_id,'is_active'=>true]);$workflow->steps()->create(['step_order'=>1,'approver_type'=>'ROLE','approver_reference'=>$role->id,'is_required'=>true,'allow_reject'=>true,'allow_revision'=>true]);$instance=app(WorkflowService::class)->start($document,$workflow,$creator);$approval=$instance->approvals()->first();$this->actingAs($approver)->post(route('approvals.action',$approval),['action'=>'REVISION_REQUESTED','notes'=>'Perbaiki isi'])->assertRedirect();$document->refresh();$this->assertSame('REVISION_REQUIRED',$document->status);$this->actingAs($creator)->put(route('documents.update',$document),['subject'=>'Versi revisi','content'=>'Isi baru'])->assertRedirect();$this->actingAs($creator)->post(route('documents.resubmit',$document))->assertRedirect();$this->assertDatabaseHas('workflow_approvals',['workflow_instance_id'=>$instance->id,'cycle'=>2,'status'=>'PENDING']);}
}
