<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
if (!Schema::hasColumn('documents','archived_at')) Schema::table('documents',fn(Blueprint $t)=>$t->timestamp('archived_at')->nullable()->index());
if (!Schema::hasTable('document_metadata')) Schema::create('document_metadata',function(Blueprint $t){$t->id();$t->foreignId('document_id')->unique()->constrained()->cascadeOnDelete();$t->json('data')->nullable();$t->timestamps();});
if (!Schema::hasTable('numbering_rules')) Schema::create('numbering_rules',function(Blueprint $t){$t->id();$t->foreignId('document_type_id')->constrained()->cascadeOnDelete();$t->foreignId('unit_id')->nullable()->constrained()->nullOnDelete();$t->string('format')->default('{SEQ}/{UNIT}/{DOCUMENT_TYPE}/{ROMAN_MONTH}/{YEAR}');$t->string('reset_period')->default('YEARLY');$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['document_type_id','unit_id']);});
if (!Schema::hasTable('numbering_sequences')) Schema::create('numbering_sequences',function(Blueprint $t){$t->id();$t->foreignId('numbering_rule_id')->constrained()->cascadeOnDelete();$t->string('period_key');$t->unsignedInteger('last_value')->default(0);$t->timestamps();$t->unique(['numbering_rule_id','period_key']);});
if (!Schema::hasTable('document_templates')) Schema::create('document_templates',function(Blueprint $t){$t->id();$t->string('name');$t->foreignId('document_type_id')->constrained()->cascadeOnDelete();$t->foreignId('unit_id')->nullable()->constrained()->nullOnDelete();$t->longText('content')->nullable();$t->longText('header')->nullable();$t->longText('footer')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
if (!Schema::hasTable('generated_documents')) Schema::create('generated_documents',function(Blueprint $t){$t->id();$t->foreignId('document_id')->unique()->constrained()->cascadeOnDelete();$t->foreignId('template_id')->nullable()->constrained('document_templates')->nullOnDelete();$t->longText('html_snapshot');$t->longText('data_snapshot');$t->string('pdf_path')->nullable();$t->string('signature_provider')->nullable();$t->string('signature_status')->default('UNSIGNED');$t->timestamps();});
} public function down():void { foreach(['generated_documents','document_templates','numbering_sequences','numbering_rules','document_metadata'] as $t)Schema::dropIfExists($t); Schema::table('documents',fn(Blueprint $t)=>$t->dropColumn('archived_at')); } };
