<?php
namespace App\Http\Controllers;
use App\Models\{Disposition,Document,Position,Unit,User}; use App\Http\Requests\StoreDispositionRequest; use App\Services\{ActivityLogService,NotificationService}; use Illuminate\Http\Request;
class DispositionController extends Controller {
 public function index(){return view('dispositions.index',['dispositions'=>Disposition::with(['document','sender','recipient'])->where('to_user_id',auth()->id())->latest()->paginate(15)]);}
 public function show(Disposition $disposition){abort_unless($disposition->to_user_id===auth()->id(),403);return view('dispositions.show',['disposition'=>$disposition->load(['document.type','sender','recipient'])]);}
 public function create(Document $document){$this->authorize('view',$document);return view('dispositions.form',['document'=>$document,'users'=>User::orderBy('name')->get(),'units'=>Unit::orderBy('name')->get(),'positions'=>Position::orderBy('name')->get()]);}
 public function store(StoreDispositionRequest $r,Document $document){$this->authorize('view',$document);$data=$r->validated();abort_if(empty($data['to_user_id'])&&empty($data['to_unit_id'])&&empty($data['to_position_id']),422,'Pilih penerima, jabatan, atau unit tujuan.');$disposition=Disposition::create([...$data,'document_id'=>$document->id,'from_user_id'=>$r->user()->id]);$document->update(['status'=>'DISPOSITIONED']);NotificationService::user($disposition->recipient,$document,'DISPOSITION_NEW','Anda menerima disposisi baru.');ActivityLogService::record($document,'CREATE_DISPOSITION',['disposition_id'=>$disposition->id,'instruction'=>$disposition->instruction,'to_user_id'=>$disposition->to_user_id,'to_unit_id'=>$disposition->to_unit_id]);return redirect()->route('documents.show',$document)->with('success','Disposisi berhasil dikirim.');}
 public function read(Disposition $disposition){abort_unless($disposition->to_user_id===auth()->id(),403);if($disposition->status==='UNREAD'){$disposition->update(['status'=>'READ','read_at'=>now()]);ActivityLogService::record($disposition->document,'READ_DISPOSITION',['disposition_id'=>$disposition->id]);}return back();}
 public function process(Disposition $disposition){abort_unless($disposition->to_user_id===auth()->id(),403);abort_if($disposition->status==='COMPLETED',422);$disposition->update(['status'=>'IN_PROGRESS','processed_at'=>now(),'read_at'=>$disposition->read_at??now()]);ActivityLogService::record($disposition->document,'PROCESS_DISPOSITION',['disposition_id'=>$disposition->id]);return back()->with('success','Disposisi sedang diproses.');}
 public function complete(Disposition $disposition){abort_unless($disposition->to_user_id===auth()->id(),403);$disposition->update(['status'=>'COMPLETED','completed_at'=>now()]);ActivityLogService::record($disposition->document,'COMPLETE_DISPOSITION',['disposition_id'=>$disposition->id]);return back()->with('success','Tindak lanjut disposisi selesai.');}
}
