<?php
namespace App\Http\Controllers;
use App\Models\{Document,DocumentType,Unit,User}; use App\Services\{ActivityLogService,WorkflowService}; use Illuminate\Http\Request; use Illuminate\Support\Str;
class DocumentController extends Controller {
 public function index(Request $r){abort_unless($r->user()->hasPermission('view documents'),403);$q=Document::with(['type','creator','unit','workflowInstance']);if(!$r->user()->hasPermission('view all documents'))$q->where('creator_id',$r->user()->id);$q->when($r->filled('search'),fn($q)=>$q->where(fn($x)=>$x->where('subject','like','%'.$r->search.'%')->orWhere('number','like','%'.$r->search.'%')))->when($r->filled('status'),fn($q)=>$q->where('status',$r->status))->when($r->filled('unit_id'),fn($q)=>$q->where('unit_id',$r->unit_id))->when($r->filled('document_type_id'),fn($q)=>$q->where('document_type_id',$r->document_type_id))->when($r->filled('creator_id'),fn($q)=>$q->where('creator_id',$r->creator_id))->when($r->filled('year'),fn($q)=>$q->whereYear('document_date',$r->year));return view('documents.index',['documents'=>$q->latest()->paginate((int)$r->input('per_page',15))->withQueryString(),'units'=>Unit::orderBy('name')->get(),'types'=>DocumentType::orderBy('name')->get(),'creators'=>User::orderBy('name')->get()]);}
 public function create(){$this->authorize('create',Document::class);return view('documents.form',['types'=>DocumentType::orderBy('name')->get(),'units'=>Unit::orderBy('name')->get()]);}
 public function store(Request $r){$this->authorize('create',Document::class);$data=$r->validate(['document_type_id'=>['required','exists:document_types,id'],'unit_id'=>['nullable','exists:units,id'],'subject'=>['required','string','max:255'],'content'=>['nullable','string'],'deadline'=>['nullable','date']]);$doc=Document::create([...$data,'creator_id'=>$r->user()->id,'uuid'=>(string)Str::uuid(),'verification_token'=>Str::random(48)]);ActivityLogService::record($doc,'CREATE_DOCUMENT',$data);return redirect()->route('documents.show',$doc)->with('success','Dokumen draft berhasil dibuat.');}
 public function show(Document $document){$this->authorize('view',$document);return view('documents.show',['document'=>$document->load(['type','creator','unit','files','dispositions.sender','dispositions.recipient','activityLogs.user','workflowInstance.workflow.steps','workflowInstance.approvals.approver','workflowInstance.approvals.step']),'availableWorkflows'=>\App\Models\Workflow::where('document_type_id',$document->document_type_id)->where('is_active',true)->where(fn($q)=>$q->whereNull('unit_id')->orWhere('unit_id',$document->unit_id))->get()]);}
 public function edit(Document $document){$this->authorize('update',$document);return view('documents.edit',compact('document'));}
 public function update(Request $r,Document $document){$this->authorize('update',$document);$data=$r->validate(['subject'=>['required','string','max:255'],'content'=>['nullable','string']]);$old=$document->only(['subject','content']);$document->update($data);ActivityLogService::record($document,'UPDATE_DOCUMENT',$data,$old);return redirect()->route('documents.show',$document)->with('success','Perbaikan dokumen disimpan.');}
 public function resubmit(Document $document,WorkflowService $workflows){$this->authorize('submit',$document);$workflows->resubmit($document->workflowInstance()->firstOrFail(),request()->user());return redirect()->route('documents.show',$document)->with('success','Dokumen dikirim kembali untuk ditinjau.');}
}
